"""add indexes on profiles table

Revision ID: 1a65bf5e1e78
Revises: 30076b6eb5dd
Create Date: 2026-04-24 09:28:09.681567

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1a65bf5e1e78'
down_revision: Union[str, Sequence[str], None] = '30076b6eb5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profiles_age'), 'profiles', ['age'], unique=False)
    op.create_index(
        op.f('ix_profiles_age_group'),
        'profiles',
        ['age_group'],
        unique=False)
    op.create_index(
        op.f('ix_profiles_country_id'),
        'profiles',
        ['country_id'],
        unique=False)
    op.create_index(
        op.f('ix_profiles_created_at'),
        'profiles',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('ix_profiles_gender'),
        'profiles',
        ['gender'],
        unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_gender'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_country_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_age_group'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_age'), table_name='profiles')
    # ### end Alembic commands ###
